name: beta-MW-dwarfs

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - jupyter
  - numpy
  - scipy
  - matplotlib
  - pandas
  - astropy
  - emcee
  - corner
  - pyyaml
  - halotools
